CREATE TABLE IF NOT EXISTS users (username TEXT PRIMARY KEY, hood TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY, username TEXT NOT NULL, hood TEXT NOT NULL, text TEXT NOT NULL, likes INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
