"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

export default function AuthForm({ mode, nextPath = "/" }: { mode: "login" | "signup"; nextPath?: string }) {
  const isSignup = mode === "signup";
  const [form, setForm] = useState({ name: "", email: "", password: "", phone: "", role: "SEEKER" });
  const [error, setError] = useState("");
  const [pending, setPending] = useState(false);
  const update = (name: string, value: string) => setForm((current) => ({ ...current, [name]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setError(""); try { const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "We could not complete that request."); window.location.assign(nextPath); } catch (reason) { setError(reason instanceof Error ? reason.message : "We could not complete that request."); setPending(false); } }
  return <form className="auth-card" onSubmit={submit}><div className="auth-card-heading"><p className="eyebrow">{isSignup ? "Join the neighbourhood" : "Welcome back"}</p><h1>{isSignup ? <>Make your next<br /><i>move a good one.</i></> : <>Good to<br /><i>see you again.</i></>}</h1><p>{isSignup ? "Create an account to save your search and start real conversations." : "Log in to manage your listings and conversations."}</p></div>{isSignup && <label>Full name<input required autoComplete="name" value={form.name} onChange={(event) => update("name", event.target.value)} />{error && error.includes("name") && <small className="field-error">{error}</small>}</label>}<label>Email address<input required type="email" autoComplete="email" value={form.email} onChange={(event) => update("email", event.target.value)} /></label>{isSignup && <label>Phone number<input required type="tel" autoComplete="tel" placeholder="07XX XXX XXX" value={form.phone} onChange={(event) => update("phone", event.target.value)} /></label>}<label>Password<input required minLength={isSignup ? 8 : 1} type="password" autoComplete={isSignup ? "new-password" : "current-password"} value={form.password} onChange={(event) => update("password", event.target.value)} />{isSignup && <span className="field-hint">Use at least 8 characters.</span>}</label>{isSignup && <label>What brings you to Naihood?<select value={form.role} onChange={(event) => update("role", event.target.value)}><option value="SEEKER">I am looking for a place</option><option value="AGENT">I own or represent properties</option></select></label>}{error && !error.includes("name") && <p className="form-error" role="alert">{error}</p>}<button className="publish-button" type="submit" disabled={pending}>{pending ? "Please wait..." : isSignup ? "Create my account ↗" : "Log in ↗"}</button>{!isSignup && <Link className="forgot-link" href="/login">Forgot your password?</Link>}<p className="auth-switch">{isSignup ? "Already have an account?" : "New to Naihood?"} <Link href={isSignup ? "/login" : "/signup"}>{isSignup ? "Log in" : "Create an account"}</Link></p></form>;
}
